public with sharing class Exceptions {

    public class OSPlacesException extends Exception {}

    public class GovNotifyException extends Exception {}

    public class QueryException extends Exception {}

    public class CustomException extends Exception {}

    public class JWTVerificationException extends Exception {}
    
    public class TokenVerificationException extends Exception {}

    public class MockConstructorOnlyException extends Exception {}

    public class MockException extends Exception {}

    public class InvalidArgumentException extends Exception {}
}